"""Curated authoritative Memory plus explicit Phase 7B retrieval."""

from memory.base import MemoryStore, StructuredProfileStore
from memory.context import MemoryContextBuilder
from memory.embeddings import (
    DEFAULT_LOCAL_MODEL_CACHE,
    DEFAULT_LOCAL_MODEL_ID,
    EmbeddingProvider,
    FakeEmbeddingProvider,
    LocalEmbeddingProvider,
)
from memory.models import (
    DimensionCardinality,
    HybridMemoryRetrievalResult,
    MemoryAuthorityLabel,
    MemoryAwareStatement,
    MemoryChangeCandidate,
    MemoryChangeChoice,
    MemoryChangeStatus,
    MemoryConsumer,
    MemoryContext,
    MemoryContextPolicy,
    MemoryRecord,
    MemoryRetrievalResult,
    MemoryStatus,
    MemoryStatementKind,
    MemoryType,
    MemoryUseCase,
    ProfileRefinementContext,
    ProfileRefinementResult,
    ProfileReference,
    ProfileSaveResult,
    PurgeResult,
    SemanticMemoryRetrievalResult,
    SessionSignalPersistence,
    StructuredSessionSignal,
    VectorIndexEntry,
    new_memory_id,
    new_subject_id,
)
from memory.integration import (
    MemoryChangeDetector,
    MemoryChangeService,
    MemoryContextCoordinator,
    MemoryPolicyRegistry,
    MemoryQueryBuilder,
    MemoryReferenceResolver,
    ProfileRefinementService,
    RoleMemoryContextService,
    StructuredSignalPolicyRegistry,
)
from memory.retriever import DeterministicMemoryRetriever, MemoryRetriever
from memory.semantic import HybridMemoryRetriever, SemanticMemoryRetriever
from memory.service import (
    MemoryService,
    build_semantic_memory_service,
    build_sqlite_memory_service,
)
from memory.sqlite_store import (
    DEFAULT_MEMORY_DATABASE_PATH,
    MEMORY_SCHEMA_VERSION,
    SQLiteMemoryDatabase,
    SQLiteMemoryStore,
    SQLiteStructuredProfileStore,
)
from memory.vector_index import (
    DEFAULT_VECTOR_DATABASE_PATH,
    VECTOR_INDEX_SCHEMA_VERSION,
    MemoryVectorIndex,
)

__all__ = [
    "DEFAULT_MEMORY_DATABASE_PATH",
    "DEFAULT_VECTOR_DATABASE_PATH",
    "DEFAULT_LOCAL_MODEL_CACHE",
    "DEFAULT_LOCAL_MODEL_ID",
    "MEMORY_SCHEMA_VERSION",
    "DeterministicMemoryRetriever",
    "DimensionCardinality",
    "EmbeddingProvider",
    "FakeEmbeddingProvider",
    "HybridMemoryRetriever",
    "HybridMemoryRetrievalResult",
    "LocalEmbeddingProvider",
    "MemoryAuthorityLabel",
    "MemoryAwareStatement",
    "MemoryChangeCandidate",
    "MemoryChangeChoice",
    "MemoryChangeDetector",
    "MemoryChangeService",
    "MemoryChangeStatus",
    "MemoryConsumer",
    "MemoryContext",
    "MemoryContextBuilder",
    "MemoryContextCoordinator",
    "MemoryContextPolicy",
    "MemoryPolicyRegistry",
    "MemoryQueryBuilder",
    "MemoryRecord",
    "MemoryReferenceResolver",
    "MemoryRetrievalResult",
    "MemoryRetriever",
    "MemoryService",
    "MemoryStatus",
    "MemoryStatementKind",
    "MemoryStore",
    "MemoryType",
    "MemoryUseCase",
    "MemoryVectorIndex",
    "ProfileRefinementContext",
    "ProfileRefinementResult",
    "ProfileRefinementService",
    "ProfileReference",
    "ProfileSaveResult",
    "PurgeResult",
    "RoleMemoryContextService",
    "SemanticMemoryRetriever",
    "SemanticMemoryRetrievalResult",
    "SessionSignalPersistence",
    "SQLiteMemoryDatabase",
    "SQLiteMemoryStore",
    "SQLiteStructuredProfileStore",
    "StructuredProfileStore",
    "StructuredSessionSignal",
    "StructuredSignalPolicyRegistry",
    "VECTOR_INDEX_SCHEMA_VERSION",
    "VectorIndexEntry",
    "build_semantic_memory_service",
    "build_sqlite_memory_service",
    "new_memory_id",
    "new_subject_id",
]
