"""Small, code-owned clarification scope; not a completeness checklist."""

from enum import Enum

MAX_SOURCES = 36
MAX_SOURCE_CHARS = 600
MAX_CONTEXT_CHARS = 18_000
MAX_NEEDS = 8
MAX_REFS = 8
MAX_QUESTIONS = 8  # Explicit user-driven turns, never an autonomous loop.
MAX_ANSWERS = 8
MAX_EVENTS = 40
PROMPT_NAME = "clarification"
PROMPT_VERSION = "v1"


class ReasonCode(str, Enum):
    MISSING_GOAL = "MISSING_GOAL"
    AMBIGUOUS_RESPONSIBILITY = "AMBIGUOUS_RESPONSIBILITY"
    UNCLEAR_SKILL_DEPTH = "UNCLEAR_SKILL_DEPTH"
    UNCLEAR_ACHIEVEMENT_OWNERSHIP = "UNCLEAR_ACHIEVEMENT_OWNERSHIP"
    CURRENT_PREFERENCE_UNKNOWN = "CURRENT_PREFERENCE_UNKNOWN"
    PROFILE_RESUME_CONFLICT = "PROFILE_RESUME_CONFLICT"
    OUTDATED_INFORMATION = "OUTDATED_INFORMATION"
    AMBIGUOUS_TRANSITION_INTENT = "AMBIGUOUS_TRANSITION_INTENT"
    UNCLEAR_DOMAIN_DEPTH = "UNCLEAR_DOMAIN_DEPTH"
    INSUFFICIENT_ROLE_CONTEXT = "INSUFFICIENT_ROLE_CONTEXT"


class TurnIntent(str, Enum):
    RESUME_REVIEW = "resume_review"
    ANSWER = "answer"
    GENERAL_QA = "general_qa"
    UNRELATED = "unrelated"


class ClarificationStatus(str, Enum):
    IDLE = "IDLE"
    QUESTION_OPEN = "QUESTION_OPEN"
    ANSWER_RECORDED = "ANSWER_RECORDED"
    NO_CLARIFICATION_NEEDED = "NO_CLARIFICATION_NEEDED"
    CLARIFICATION_CONTEXT_FAILED = "CLARIFICATION_CONTEXT_FAILED"
    INVALID_CLARIFICATION_PLAN = "INVALID_CLARIFICATION_PLAN"
    INVALID_REFERENCE = "INVALID_REFERENCE"
    PROVIDER_FAILED = "PROVIDER_FAILED"
    STALE_CLARIFICATION_STATE = "STALE_CLARIFICATION_STATE"
    ANSWER_NOT_APPLICABLE = "ANSWER_NOT_APPLICABLE"
